services:
  http1-vs-http2:
    container_name: http1-vs-http2
    image: nginx:1.20.2-alpine
    ports:
      - 441:441
      - 442:442
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./static:/usr/share/nginx/html:ro
